runtime: python39

entrypoint: gunicorn -b :$PORT main:app

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic

env_variables:
  SECRET_KEY: "a866a2f2dc79655511e4a2e81ecac3ad837877d8807635e774606ff02e02b29e"
  GEMINI_API_KEY: "your_gemini_api_key"
  GOOGLE_MAPS_API_KEY: "your_google_maps_api_key"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto